version: '2.4'

services:
  # docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      xpack.security.enabled: 'false'
      discovery.type: single-node
      http.port: 9200
    volumes:
    - type: volume
      source: data_elk
      target: /usr/share/elasticsearch/data:rw
    networks: ['elk_network']
    ports: ['9200:9200']

  # docs: https://www.elastic.co/guide/en/kibana/current/index.html
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      SERVER_PORT: 5601
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      XPACK_SECURITY_ENABLED: 'true'
    networks: ['elk_network']
    ports: ['5601:5601']

  # docs: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-overview.html
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.7.0
    container_name: filebeat
    hostname: filebeat
    volumes:
    - type: bind
      source: ./configs/filebeat.yml
      target: /usr/share/filebeat/filebeat.yml
      read_only: true
    - type: bind
      source: ./data/data.log
      target: /mnt/data/data.log
      read_only: true
    networks: ['elk_network']

volumes:
  data_elk:
    name: data_elk
    driver: local

networks:
  elk_network:
    name: elk_network
    driver: bridge
