version: '2.4'

services:
  # docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
  elasticsearch:
    image: elasticsearch:8.9.1
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      xpack.security.enabled: 'false'
      discovery.type: single-node
      http.port: 9200
    volumes:
    - type: volume
      source: data_elk
      target: /usr/share/elasticsearch/data:rw
    networks: ['elk_network']
    ports: ['9200:9200']

  # docs: https://www.elastic.co/guide/en/kibana/current/index.html
  kibana:
    image: kibana:8.9.1
    container_name: kibana
    hostname: kibana
    environment:
      SERVER_NAME: kibana
      SERVER_PORT: 5601
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      XPACK_SECURITY_ENABLED: 'true'
    networks: ['elk_network']
    ports: ['5601:5601']

volumes:
  data_elk:
    name: data_elk
    driver: local

networks:
  elk_network:
    name: elk_network
    driver: bridge
