Vagrant.configure(2) do |config| 
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.cpus = "1"
        v.memory = "1024"
        v.check_guest_additions = false
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
  
    config.vm.define "kibana" do |kibana|
        kibana.vm.network "public_network", ip: "192.168.1.50", bridge: "enp1s0f1"
        kibana.vm.hostname = "kibana"
        # script
        # kibana.vm.provision "shell", path: "script.sh"
        
        # shell
        # kibana.vm.provision "shell", inline: <<-SHELL
        # SHELL
        
        # ansible 
        # kibana.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
  
    config.vm.define "elastic" do |elastic| 
        elastic.vm.network "public_network", ip: "192.168.1.51", bridge: "enp1s0f1"
        elastic.vm.hostname = "elastic"
  
        # script
        # elastic.vm.provision "shell", path: "script.sh"
        
        # shell
        # elastic.vm.provision "shell", inline: <<-SHELL
        # SHELL
  
        # ansible
        # elastic.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
  end 