path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

discovery.seed_hosts: ["0.0.0.0"]
discovery.type: single-node

xpack.security.enabled: true
xpack.security.enrollment.enabled: true


#xpack.security.http.ssl:
#  enabled: true
#  keystore.path: certs/http.p12

#xpack.security.transport.ssl:
#  enabled: true
#  verification_mode: certificate
#  keystore.path: certs/transport.p12
#  truststore.path: certs/transport.p12

xpack.security.authc.api_key.enabled: true

network.host: 0.0.0.0
http.host: 0.0.0.0
