# filebeat.inputs:
#   - type: log
#     paths:
#       - /mnt/data/data.log
#     fields:
#       device_name: macbook
#     fields_under_root: true
#     enabled: true

# filebeat.inputs:
#   - type: log
#     paths:
#       # run 'sudo chmod o+r /var/log/auth.log' to avoid to permission denied (in the system, not in the container)
#       - /mnt/var/log/auth.log
#     fields:
#       device_name: ubuntu
#     fields_under_root: true
#     processors:
#      - drop_fields:
#          fields: ["log.offset"]
#     enabled: true

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]

# output.console:
#   pretty: true
#   enabled: false
