Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../shared", "/shared", disabled: false
    config.vm.provider "virtualbox" do |vms|
        # vms.gui = false
        vms.check_guest_additions = false
        vms.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end

    config.vm.define "elk" do |elk|
        elk.vm.box = "bento/ubuntu-22.04"
        elk.vm.network "public_network", ip: "192.168.1.50", bridge: "enp1s0f1"
        # TO DO: private network, NAT and port forwarding
        elk.vm.hostname = "elk"
        elk.vm.provider "virtualbox" do |vm1|
            vm1.memory = "4096"
            vm1.cpus = "2"
        end

        # script
        # elk.vm.provision "shell", path: "script.sh"

        # shell
        elk.vm.provision "shell", inline: <<-SHELL
            # Elasticsearch
            # https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html#install-deb
            sudo dpkg -i /shared/packages/elasticsearch-8.12.0-amd64.deb
            sudo cp /shared/configs/elasticsearch/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
            sudo /bin/systemctl daemon-reload
            sudo /bin/systemctl enable elasticsearch.service
            # --- manual {
            # sudo /usr/share/elasticsearch/bin/elasticsearch-keystore list
            # sudo /usr/share/elasticsearch/bin/elasticsearch-keystore create
            # sudo systemctl start elasticsearch.service
            # sudo /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
            # export ELASTIC_PASSWORD=
            # sudo systemctl restart elasticsearch.service
            # curl -u elastic:$ELASTIC_PASSWORD localhost:9200?pretty
            # --- } manual
            # TO DO:
            # export ELASTIC_PASSWORD=$ELASTIC_PASSWORD

            # Kibana
            # https://www.elastic.co/guide/en/kibana/current/deb.html#install-deb
            sudo dpkg -i /shared/packages/kibana-8.12.0-amd64.deb
            sudo cp /shared/configs/kibana/kibana.yml /etc/kibana/kibana.yml
            sudo /bin/systemctl enable kibana.service
            # --- manual {
            # sudo /usr/share/kibana/bin/kibana-keystore add elasticsearch.username {kibana_system}
            # sudo /usr/share/kibana/bin/kibana-keystore add elasticsearch.password
            # sudo systemctl start kibana.service
            # --- } manual
            # TO DO:
            # xpack.encryptedSavedObjects.encryptionKey: $ENCRYPTION_KEY
        SHELL

        # ansible
        # elk.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end

    config.vm.define "victim" do |victim|
        victim.vm.box = "gusztavvargadr/windows-server"
        victim.vm.network "public_network", ip: "192.168.1.51", bridge: "enp1s0f1"
        victim.vm.hostname = "victim-windows"
        victim.vm.provider "virtualbox" do |vm2|
            vm2.memory = "2048"
            vm2.cpus = "2"
        end

        # script
        # victim.vm.provision "shell", path: "script.sh"

        # shell
        # victim.vm.provision "shell", inline: <<-SHELL
        # SHELL

        # ansible
        # victim.vm.provision "ansible" do |ansible|
        #     ansible.verbose = "vv"
        #     ansible.playbook = "provision/playbook.yml"
        #     ansible.become = "true"
        # end
    end
end